In [5]:
#load the iris dataset as an example
from sklearn.datasets import load_iris
import numpy as np
iris=load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [6]:
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [7]:
#store the feature matrix(X) and response vector (y)
X=iris.data
y=iris.target

print("X ",X[:5])
print("y ",y[:5])

X  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
y  [0 0 0 0 0]


In [8]:
#splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=1)

print(iris.data.shape)
print(len(X_train))
print(len(y_test))

(150, 4)
90
60


In [9]:
#training the model on training set
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3) #should be odd, usually equal to no. of class labels
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [10]:
#making predictions on the testing set
y_pred=knn.predict(X_test)
print(y_pred)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 1 2 1 2 0 0 0 1 0 0 2 2 2 2 2 1 2 1]


In [11]:
#comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("Accuracy = ",metrics.accuracy_score(y_test,y_pred))

Accuracy =  0.9833333333333333


In [15]:
print("confusion Matrix:\n",metrics.confusion_matrix(y_test,y_pred))

confusion Matrix:
 [[19  0  0]
 [ 0 21  0]
 [ 0  1 19]]


In [16]:
#printing output of entire test_dataset
preds=knn.predict(X_test)
pred_species=[iris.target_names[p] for p in preds]
pred_species1=[iris.target_names[p] for p in y_test]

print("\tPredicted","\t\tActual","\t\tAnswer")
for i in range(0,len(pred_species)):
    print(i,":",pred_species[i],"\t\t",pred_species1[i],"\t\t",end='\t')    
    if(pred_species[i]==pred_species1[i]):
        print("Correct")
    else:
        print("Incorrect!!!")

	Predicted 		Actual 		Answer
0 : setosa 		 setosa 			Correct
1 : versicolor 		 versicolor 			Correct
2 : versicolor 		 versicolor 			Correct
3 : setosa 		 setosa 			Correct
4 : virginica 		 virginica 			Correct
5 : versicolor 		 versicolor 			Correct
6 : virginica 		 virginica 			Correct
7 : setosa 		 setosa 			Correct
8 : setosa 		 setosa 			Correct
9 : virginica 		 virginica 			Correct
10 : versicolor 		 versicolor 			Correct
11 : setosa 		 setosa 			Correct
12 : virginica 		 virginica 			Correct
13 : versicolor 		 versicolor 			Correct
14 : versicolor 		 versicolor 			Correct
15 : setosa 		 setosa 			Correct
16 : versicolor 		 versicolor 			Correct
17 : versicolor 		 versicolor 			Correct
18 : setosa 		 setosa 			Correct
19 : setosa 		 setosa 			Correct
20 : versicolor 		 versicolor 			Correct
21 : versicolor 		 versicolor 			Correct
22 : versicolor 		 versicolor 			Correct
23 : setosa 		 setosa 			Correct
24 : virginica 		 virginica 			Correct
25 : versicolor 		 versicolor 			Corre

In [ ]:
#checking for sample: wrong prediction
sample=[X_test[42]]
print(sample)
ps=knn.predict(sample)
print(iris.target_names[ps])